### PR TITLE
Colorize character matches in the command palette

### PR DESCRIPTION
**Pull request by simurai**
### Before

Only happened when switching themes, see https://github.com/atom/one-light-ui/issues/70#issuecomment-261812610.

atom hl

### After

screen shot 2016-11-22 at 6 53 09 pm

Fixes https://github.com/atom/one-light-ui/issues/70

### CODE REVIEW

**Comment by jerone** [comment]
Have you considered a (yellow) background-color?

**Comment by thomasjo** [comment]
> Have you considered a (yellow) background-color?

We don't pick colors, since that breaks the whole adaptive accent scheme. The colors are always based on the syntax theme.

Using a background color would likely look really odd, especially given that font widths are not uniform, so you'd have non-uniform width "boxes" all over the place.

**Comment by jerone** [comment]
A yellow background-color for search results is probably [used most often](https://www.google.nl/search?q=search+highlight&source=lnms&tbm=isch). Sure this can conflict with some themes, but they can always override.

> We don't pick colors, since that breaks the whole adaptive accent scheme. The colors are always based on the syntax theme.

Isn't [`accent-color`](https://github.com/atom/one-light-ui/blob/399660ce9888e506a7d82145ab9bbc9d6f22e77d/styles/ui-variables-custom.less#L52) part of this theme...

I can always use my own in `styles.less`: 
```css
.command-palette .list-group .character-match,
.fuzzy-finder .list-group .character-match {
  background-color: #ffff22;
}
```

**Comment by thomasjo** [comment]
If you look at the stylesheet you linked more closely, you'll notice the `.ui-hue()` function a few lines higher up, which ends up being computed based on `@syntax-background-color`.

**Comment by simurai** [comment]
> Have you considered a (yellow) background-color?

For light backgrounds that would work well. It's like those yellow markers.. 

screen shot 2016-11-23 at 2 31 54 pm

but yeah.. For dark maybe a bit too strong.

screen shot 2016-11-24 at 9 35 04 am

Could be faded, but that could also look too muddy?

screen shot 2016-11-24 at 9 45 15 am

Ooooor... underlines!!!

screen shot 2016-11-24 at 9 48 49 am

Hmmm.. So many options.. :see_no_evil:

**Comment by simurai** [comment]
ok, how about we keep the accent color so that it matches with the border color of the input. I 🎻  fiddled a bit more with the contrast.

> @jerone I can always use my own in styles.less:

Yeah, feel free to customize further it even further.

**Comment by simurai** [comment]
And while we're at it, let's also change the keybindings to:

screen shot 2016-11-24 at 3 03 42 pm

**Pull request merged**
