### PR TITLE
Replace tree-view focus indicator

### PR DESCRIPTION
**Pull request by simurai**
Same as https://github.com/atom/one-dark-ui/pull/229

### CODE REVIEW

**Comment by 50Wliu** [comment]
@simurai this is causing low contrast issues for me.
tree-view-low-contrast-unmodified
tree-view-low-contrast-modified
tree-view-low-contrast-new

All three combinations fail WCAG AA, with contrast ratios of 4.33:1, 1.18:1, and 1.24:1 respectively.  The github package solved this by switching to white text when focused.  But this will be trickier given the different VCS coloring.

**Comment by 50Wliu** [comment]
Oh also, it makes some icons basically invisible.
tree-view-low-contrast-file-icon

**Comment by simurai** [comment]
Ouch.. sorry. I didn't test this enough.

> But this will be trickier given the different VCS coloring.

Right, we could make it white like the GitHub package:

tree-view

but VCS coloring would be lost.

Find another way to show VCS status? Like https://atom.io/themes/city-lights-ui has this circles on the right.
 
image

**Comment by simurai** [comment]
Found another bug:

image

**Comment by simurai** [comment]
Tried out a "dot version":

image

But it also makes the tree-view more busy. For now I went with the first version ☝️  https://github.com/atom/one-light-ui/pull/117

**Pull request merged**
